/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#bf3c25",
        "error-container": "#93000a",
        "primary-fixed": "#98f6bc",
        "secondary-container": "#42474f",
        "surface-variant": "#31353c",
        "surface-container-low": "#181c22",
        "secondary-fixed-dim": "#c2c7d0",
        "on-secondary-container": "#b1b5bf",
        "on-primary": "#00391f",
        "on-tertiary-fixed-variant": "#8d1704",
        "surface": "#10141a",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#006d41",
        "on-primary-container": "#a6ffc7",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#171c23",
        "outline-variant": "#3f4941",
        "on-surface": "#dfe2eb",
        "primary-fixed-dim": "#7cd9a1",
        "secondary-fixed": "#dee2ec",
        "outline": "#88948a",
        "inverse-surface": "#dfe2eb",
        "on-secondary-fixed-variant": "#42474f",
        "background": "#10141a",
        "tertiary-fixed-dim": "#ffb4a5",
        "surface-tint": "#7cd9a1",
        "on-error": "#690005",
        "on-secondary": "#2c3138",
        "on-surface-variant": "#becabf",
        "surface-dim": "#10141a",
        "tertiary": "#ffb4a5",
        "surface-container-highest": "#31353c",
        "on-tertiary": "#650a00",
        "primary-container": "#0f7a4b",
        "on-tertiary-fixed": "#3f0400",
        "surface-bright": "#353940",
        "surface-container": "#1c2026",
        "tertiary-fixed": "#ffdad3",
        "on-primary-fixed-variant": "#005230",
        "surface-container-high": "#262a31",
        "surface-container-lowest": "#0a0e14",
        "on-tertiary-container": "#ffe6e1",
        "primary": "#7cd9a1",
        "on-primary-fixed": "#002110",
        "secondary": "#c2c7d0",
        "inverse-on-surface": "#2d3137",
        "on-background": "#dfe2eb"
      },
      spacing: {
        "gutter": "16px",
        "xl": "48px",
        "base": "4px",
        "container-margin": "20px",
        "lg": "32px",
        "sm": "16px",
        "md": "24px",
        "xs": "8px"
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        "price-display": ["Geist", "monospace"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["Geist", "monospace"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "headline-xl": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"]
      },
      fontSize: {
        "price-display": ["22px", { lineHeight: "22px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
};
